language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-sydney-devfest2018
  token:
    secure: fPOKFVgJTWgDYbubOxFNg6S2sPPktJD5uefEIUx77RqJIguO1EaSOBzyaLBT/qSknP3epiFA+RCy2LS5zFgdo++tVAF5EIjVWuW4DnSCkACdFpRXDZQOMYq+BYJMxX99FITZslRlsmhe0bMHsjVWu+IMGSB74Jm5u59eRdL+uzKjFYyTybM30GM4yd9PO+9EgodUWlciSNWdY1ZAehsknfxNynOEpQ5YYUgUCm1a5xv85BlrTAkn1FLIFM4GP0OqiwOiYzrxPgC+Uy7N3Acal9pCHhWK1dUYeLd5SP2BZ/vES8Dmu39+bfvkGnTUeoGrs3/qpzQXra0wwYhEfwxNJAz1ZaA7pIVy4kG9xRnlVzjmWkhNG2r+aJlq+W+a4wodYDqbLobReICDgGDZ8W0uEbdHig6UVyFEj7yxB8xNYFQ1RaHj24XOjR9ZKKtIUDmsvGFsrp8EHrnwWCVeh4m0TxBNCDPMToBtO55DdjGyCLwqGlxlMqOrlnM+P4RCOHYH4Z8bgV9mMceZpowrd6lX7Y69lowJHCZVcYN+dB/vhAsvj2ai8NF6O3fXkOZGALQndn9ZUUGj+Mwgkeo7Y3O27tEBkdH/Qu+DFlmZVRbAmz3vy5mhgZ1hcN0RmBNOCY0SqRY7hXcTWCMOtaJTEg30dYlmcAHsHMgkTAQQHu1nA64=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: test-gdg-sydney-devfest2018
  token:
    secure: mcPNXDNRN9qBfnMl2zz487cBvAOCPfOCLTymncGsNoIec+AcftSGG1ZeWiXx2KZ11ksAbGhVBSg2GOIi0ty7ZtVhvldG4yxduft8i9+wKZ8qpNDG8TRIQRymF0o/+kZ0fo4U1WgWyfbj5vbL9mQcAQzuLh+/pK6/vnHxP6Rb0cNkd9pABXVRI352MVOXVxM77wrS0b2IdenB+JT67pEEHstBPDku1GW3lh2qxR7Al/sqYzPjipn+7v8cQaCpSKLuhpL2j7k/x4ZsfTs7DiTa1P/+6On2kXLCAaBGWvu8clWVTa4evvTliaPq+6VBF7eDvyjfeZCR2FVORAig+nH0pEZwXMSsZVNdlFctBXMDURo/sKHDGkqyxHG2ZLFgJxxPZxMX6teiYHvkSt/gRsUwrLpJPkUDVbGog1JgkahMK/TLbx3gNMDNxtqYETvmK2eEQTZE2wptwKxhFceFrSXAegoXVfDAXHPUWX9KpdQN2UzF12UirWwlKbSCmAomTfj2L42e+dbW4uOTftrogcI9Afm+KLw/pJIUk+r/RsdJ65ATzuO1X3rItt456q21K9PUgPVC0YxNKWB0mZJlADFk//sFTJDLolpMZy5uny5P3zkXcLhDL5BdnLBrMpKKObpTppC+auLsYHJ8y9emoEvzj1trGve4So0OVWytpIxlkBE=

