language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-sydney-devfest2018
  token:
    secure: "MSQQgf9ER5fESACnPrHP0DSGcuHg7GFKIJGMeSDmSk9zuMwbfmymV5qK+0IEKpwDHWn+2Um1F5ThI1Y1/EkJ1TYr62pfhqwq0KSWuIha8u/ZSV30FAJZw93n/SiqpyfUo8MTGmW8xBi+nYUHgqjUwKvEiKXsro9NUIzbJRL3VRWi/b5bBsaKD+FJu/g/n1FguAWU+iVu31KhrlIfQ7zab/m7WyQzoEc+R2DQpQ7ryvbthMJUF8PYIL2sD+mrMCNwDhn5/Vtcviok51sfPLZtWxgiWrpuBYn03Lkl5XdyIGdg0+7P6CnkNo5CFrti6vgU/SEp6t3jWhTXQKj/PhH6oriiWukFYOziOxaHUvhLf63kRiT8phZ4GUak7TtngsPY8gM4/Aa3yB7D3o0jIk9Zz9M94UwJm//O4UQzNzVVqSqDx59YOATXZM/Bx9XPvvKdT06OihBpazicxSiXeh9LHS9J25d9RUfThwVh/3xwOAQGGR17pxmHVkleplK+KJD3VqzgCDv9/++4O/tT/eoyOzYOgTHKvTL0pgE/bw/rzJg73CgT6XnRn1F5khhIKRXXltY8j0n8OT+OhraV9amKRpE581gLDYjv7qktY2dE1n4znNbX+bhX/cMtthyOcH4qcY9e05wThkO1UfRK8cd7cTPBSc0a3sjDg0BUew6cnZg="
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: test-gdg-sydney-devfest2018
  token:
    secure: "MSQQgf9ER5fESACnPrHP0DSGcuHg7GFKIJGMeSDmSk9zuMwbfmymV5qK+0IEKpwDHWn+2Um1F5ThI1Y1/EkJ1TYr62pfhqwq0KSWuIha8u/ZSV30FAJZw93n/SiqpyfUo8MTGmW8xBi+nYUHgqjUwKvEiKXsro9NUIzbJRL3VRWi/b5bBsaKD+FJu/g/n1FguAWU+iVu31KhrlIfQ7zab/m7WyQzoEc+R2DQpQ7ryvbthMJUF8PYIL2sD+mrMCNwDhn5/Vtcviok51sfPLZtWxgiWrpuBYn03Lkl5XdyIGdg0+7P6CnkNo5CFrti6vgU/SEp6t3jWhTXQKj/PhH6oriiWukFYOziOxaHUvhLf63kRiT8phZ4GUak7TtngsPY8gM4/Aa3yB7D3o0jIk9Zz9M94UwJm//O4UQzNzVVqSqDx59YOATXZM/Bx9XPvvKdT06OihBpazicxSiXeh9LHS9J25d9RUfThwVh/3xwOAQGGR17pxmHVkleplK+KJD3VqzgCDv9/++4O/tT/eoyOzYOgTHKvTL0pgE/bw/rzJg73CgT6XnRn1F5khhIKRXXltY8j0n8OT+OhraV9amKRpE581gLDYjv7qktY2dE1n4znNbX+bhX/cMtthyOcH4qcY9e05wThkO1UfRK8cd7cTPBSc0a3sjDg0BUew6cnZg="
env:
  global:
    secure: "MSQQgf9ER5fESACnPrHP0DSGcuHg7GFKIJGMeSDmSk9zuMwbfmymV5qK+0IEKpwDHWn+2Um1F5ThI1Y1/EkJ1TYr62pfhqwq0KSWuIha8u/ZSV30FAJZw93n/SiqpyfUo8MTGmW8xBi+nYUHgqjUwKvEiKXsro9NUIzbJRL3VRWi/b5bBsaKD+FJu/g/n1FguAWU+iVu31KhrlIfQ7zab/m7WyQzoEc+R2DQpQ7ryvbthMJUF8PYIL2sD+mrMCNwDhn5/Vtcviok51sfPLZtWxgiWrpuBYn03Lkl5XdyIGdg0+7P6CnkNo5CFrti6vgU/SEp6t3jWhTXQKj/PhH6oriiWukFYOziOxaHUvhLf63kRiT8phZ4GUak7TtngsPY8gM4/Aa3yB7D3o0jIk9Zz9M94UwJm//O4UQzNzVVqSqDx59YOATXZM/Bx9XPvvKdT06OihBpazicxSiXeh9LHS9J25d9RUfThwVh/3xwOAQGGR17pxmHVkleplK+KJD3VqzgCDv9/++4O/tT/eoyOzYOgTHKvTL0pgE/bw/rzJg73CgT6XnRn1F5khhIKRXXltY8j0n8OT+OhraV9amKRpE581gLDYjv7qktY2dE1n4znNbX+bhX/cMtthyOcH4qcY9e05wThkO1UfRK8cd7cTPBSc0a3sjDg0BUew6cnZg="
