language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-sydney-devfest2018
  token:
    secure: bhUNT3LgVkFVnznWBrpYGZO6lbIxhmTZ8Jo1Xo7TfQL7oFf9F6E8+NDmAZDgW3jBPRmVquNvmMOCCO09zEVkaTpftA/PIlaYz/nkJLVL8KLBYwSsRmJGFJaL0cri8O5mVvbUIquBZhGVUcT4oVsL8v6goyE8g2WmhqXGv7UsiW5Mc11Df7cc3E84PbBKSUYdTVLvn/PWaMXu4Wzn78nzbcE1AsqWYGyL45UmQ+rHRBv8INDr85sYjNmn1x6pnkguCdw7jYZ1DW9EaEAPjcfC5nw5vvAVTCbQLxbod2oEvVyOzhEfccrJkLtsUHdfGvJJgimBcIGA2VYOJ9Ez+QnZdtDaomGvDXVEVtwXiXd/1Y6wg/ZYyzROVRt6YAk2UfBk2FBibRYaRu7N2ALrDFbnnsVasU4n3mf6tzmkQneNkRBm+koJeLSaiVOwJs0HDbzoAvCXsmnHxap/GO86pWvPZ7MNLXwWXFMLqv3PUV3wYnLnjPU0ZlzXgr2moxKG6aX/2LemuA0YkFpqzJO3MyPtSp0Mdl7criBk/+Rb5jlWO7i/fG0GGKEjTX4ScPJJAtuqdZQbZY0hFaAW4mppS9G7mFMK2qnRSUHbzOdxxM6WIsZDtBQcBNNePt73sbH9dUbqFmttHRPelErzKlITbZtF7bD7xOy5+gkf+oUjKr+ioR0=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: test-gdg-sydney-devfest2018
  token:
    secure: bhUNT3LgVkFVnznWBrpYGZO6lbIxhmTZ8Jo1Xo7TfQL7oFf9F6E8+NDmAZDgW3jBPRmVquNvmMOCCO09zEVkaTpftA/PIlaYz/nkJLVL8KLBYwSsRmJGFJaL0cri8O5mVvbUIquBZhGVUcT4oVsL8v6goyE8g2WmhqXGv7UsiW5Mc11Df7cc3E84PbBKSUYdTVLvn/PWaMXu4Wzn78nzbcE1AsqWYGyL45UmQ+rHRBv8INDr85sYjNmn1x6pnkguCdw7jYZ1DW9EaEAPjcfC5nw5vvAVTCbQLxbod2oEvVyOzhEfccrJkLtsUHdfGvJJgimBcIGA2VYOJ9Ez+QnZdtDaomGvDXVEVtwXiXd/1Y6wg/ZYyzROVRt6YAk2UfBk2FBibRYaRu7N2ALrDFbnnsVasU4n3mf6tzmkQneNkRBm+koJeLSaiVOwJs0HDbzoAvCXsmnHxap/GO86pWvPZ7MNLXwWXFMLqv3PUV3wYnLnjPU0ZlzXgr2moxKG6aX/2LemuA0YkFpqzJO3MyPtSp0Mdl7criBk/+Rb5jlWO7i/fG0GGKEjTX4ScPJJAtuqdZQbZY0hFaAW4mppS9G7mFMK2qnRSUHbzOdxxM6WIsZDtBQcBNNePt73sbH9dUbqFmttHRPelErzKlITbZtF7bD7xOy5+gkf+oUjKr+ioR0=
